grad_clip: 5.0
batch_type: folded
batch_size: 128
max_epoch: 20
optim: adam
optim_conf:
    lr: 0.0005
lm: seq_rnn
lm_conf:
    unit: 2048
    nlayers: 4
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10